---
title: "Pop nat analysis"
author: "Laure Olazcuaga, Nicolas Rode"
date: "`r format(Sys.Date(), '%d-%B-%Y')`"
output: 
  html_document:
    theme: "journal"
    toc: true
    toc_depth: 3
    number_sections: true
    toc_float:
      collapsed: false
      smooth_scroll: false
editor_options: 
  chunk_output_type: console
---


```{r setup, include =FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
devtools::load_all()
```


# DATA 
```{r }
#############################
#PERFORMANCE 
#############################

data_PERF <- import_data(dataset = "DATACOMPLET_PERF.csv", 
                         trait = "performance",
                         remove_testenvt = c("Grape","GF"), 
                         remove_pop = c("WT3"), 
                         remove_rate = NA)

head(data_PERF)
tapply(data_PERF$Nb_adults,list(data_PERF$Original_environment,data_PERF$Generation),length)

#############################
#EMERGENCE RATE
#############################

data_PERF_Rate <- import_data(dataset = "DATACOMPLET_PERF.csv", 
                         trait = "performance",
                         remove_testenvt = c("Grape","GF"), 
                         remove_pop = c("WT3"), 
                         remove_rate = TRUE)
head(data_PERF_Rate)
tapply(data_PERF_Rate$Nb_adults,list(data_PERF_Rate$Original_environment,
                                     data_PERF_Rate$Generation),length)

tapply(data_PERF_Rate$Rate,data_PERF_Rate$Generation,mean)

## To test Rate higher than 1
# data_PERF_Rate <- import_data(dataset = "DATACOMPLET_PERF.csv", 
#                          trait = "performance",
#                          remove_testenvt = c("Grape","GF"), 
#                          remove_pop = c("WT3"), 
#                          remove_rate = NA)
# #Replace Rate>1 by 1
# data_PERF_Rate$Rate[data_PERF_Rate$Nb_adults>=data_PERF_Rate$Nb_eggs] <- 1

###########################
#PREFERENCE 
###########################
data_PREF <- import_data(dataset = "DATACOMPLET_PREF.csv", 
                         trait = "preference",
                         remove_testenvt = NA, 
                         remove_pop = c("WT3"), 
                         remove_rate = NA)

head(data_PREF)
tapply(data_PREF$Nb_eggs,list(data_PREF$Original_environment,data_PREF$Generation),length)



###########################
#PREFERENCE 3 fruits
###########################
levels_test<-levels(data_PREF$Test_environment)
levels_original<-levels(data_PREF$Original_environment)


data_PREF_three <- import_data(dataset = "DATACOMPLET_PREF.csv", 
                         trait = "preference",
                         remove_testenvt = usefun::outersect(levels_test, 
                                                             levels_original), 
                         remove_pop = c("WT3"), 
                         remove_rate = NA)

head(data_PREF_three)
tapply(data_PREF_three$Nb_eggs,list(data_PREF_three$Original_environment,
                                    data_PREF_three$Generation),length)

resume_design<-tapply(as.factor(data_PREF_three$BoxID),list(data_PREF_three$Population,
                                  data_PREF_three$Generation),length)
mean(resume_design[,1], na.rm = TRUE)/3
mean(resume_design[,2], na.rm = TRUE)/3

resume_design<-tapply(data_PERF$Nb_eggs,list(data_PERF$Population,
                                  data_PERF$Generation),length)
mean(resume_design[,1], na.rm = TRUE)/3
mean(resume_design[,2], na.rm = TRUE)/3

dim(data_PREF_three)
dim(data_PREF)
head(data_PREF)


levels(data_PREF$Population)
```



# CORRELATIONS BETWEEN GO and G2
## Without accounting for differences among original environments in G0
### Plot
```{r }

title_plot <- "CorrelationsG1_G3_Offspring_performance.pdf"
title_plot <- "CorrelationsG0_G2_Oviposition_Stimulation.pdf"
title_plot <- "CorrelationsG0_G2_Oviposition_Preference.pdf"

axisG0 <- "Performance G1"
axisG2 <- "Performance G3"
axisG0 <- "Oviposition stimulation G0"
axisG2 <- "Oviposition stimulation G2"
axisG0 <- "Preference G0"
axisG2 <- "Preference G2"

modelformula <- asin(sqrt(Rate))  ~ Test_environment + log(Nb_eggs) + Generation
modelformula <- log(Nb_eggs+1)  ~ Test_environment + Generation
modelformula <- log(Nb_eggs+1)  ~ Test_environment + Generation + BoxID


## Select the datasets to use for the graph
dataselect <- data_PERF_Rate
dataselect <- data_PERF
dataselect <- data_PREF_three

###PLOT 
(PAIR_G0_G2 <- plot_correlation_meanresiduals(dataset = dataselect, 
                                              formula = modelformula, 
                                              envfactor="Generation", 
                                              additional_factor="Test_environment",
                                              original_environment="Original_environment", 
                                              col_original_environment= c("#301934","#BC3C6D", "#3FAA96"),
                                              grp_cols=c("Population", "Original_environment", "Test_environment","Generation"),
                                              facetwrap=TRUE, fixedxylim = FALSE, 
                                              bisector = TRUE, xaxis_labelprint = axisG0, 
                                              yaxis_labelprint =  axisG2))



cowplot::save_plot(file =here::here("figures", title_plot),
                 PAIR_G0_G2, base_height = 10/cm(1),
                  base_width = 20/cm(1), dpi = 1200)


```

### Analyses of Emergence rate
```{r }
## Create new variable
data$City_Original_environment <- as.factor(paste(data$City, data$Original_environment, sep="_"))

## Blackberry
m00 <- lme4::lmer(asin(sqrt(Emergence_Rate))  ~ log(Nb_eggscorrected) + (0+ lme4::dummy(Generation, "G0") |  City_Original_environment) + (0+lme4::dummy(Generation, "G2")|City_Original_environment), data=data[data$Test_environment=="Blackberry"&!is.na(data$Emergence_Rate),], REML = FALSE)

m01 <- lme4::lmer(asin(sqrt(Emergence_Rate))  ~ log(Nb_eggscorrected)+ (0+Generation | City_Original_environment) , data=data[data$Test_environment=="Blackberry"&!is.na(data$Emergence_Rate),], REML = TRUE)

summary(m00)
summary(m01)
MuMIn::model.sel(m00, m01)



## Strawberry
m00 <- lme4::lmer(asin(sqrt(Emergence_Rate))  ~ log(Nb_eggscorrected) + (0+ lme4::dummy(Generation, "G0")| City_Original_environment) + (0+lme4::dummy(Generation, "G2")|City_Original_environment), data=data[data$Test_environment=="Strawberry"&!is.na(data$Emergence_Rate),], REML = TRUE)
m01 <- lme4::lmer(asin(sqrt(Emergence_Rate))  ~ log(Nb_eggscorrected) + (0+Generation|City_Original_environment) , data=data[data$Test_environment=="Strawberry"&!is.na(data$Emergence_Rate),], REML = TRUE)
MuMIn::model.sel(m00, m01)

## Cherry
m00 <- lme4::lmer(asin(sqrt(Emergence_Rate))  ~ log(Nb_eggscorrected) + (0+ lme4::dummy(Generation, "G0")| City_Original_environment) + (0+lme4::dummy(Generation, "G2")|City_Original_environment), data=data[data$Test_environment=="Cherry"&!is.na(data$Emergence_Rate),], REML = TRUE)
m01 <- lme4::lmer(asin(sqrt(Emergence_Rate))  ~ log(Nb_eggscorrected)+ (0+Generation|City_Original_environment) , data=data[data$Test_environment=="Cherry"&!is.na(data$Emergence_Rate),], REML = TRUE)
MuMIn::model.sel(m00, m01)

##Cl:Performance in G0 and G2 are not correlated

```



### Analyses of Oviposition Preference
```{r }
## Create new variable
data$City_Original_environment <- as.factor(paste(data$City, data$Original_environment, sep="_"))

## Blackberry
m00 <- lme4::lmer(log(Nb_eggs+1)  ~ BoxID + (0+ lme4::dummy(Generation, "G0") |  City_Original_environment) + (0+lme4::dummy(Generation, "G2")|City_Original_environment), data=data[data$Test_environment=="Blackberry",], REML = FALSE)

m01 <- lme4::lmer(log(Nb_eggs+1)  ~ BoxID + (0+Generation | City_Original_environment) , data=data[data$Test_environment=="Blackberry",], REML = TRUE)

summary(m00)
summary(m01)
MuMIn::model.sel(m00, m01)



## Strawberry
m00 <- lme4::lmer(log(Nb_eggs+1)  ~ BoxID + (0+ lme4::dummy(Generation, "G0") |  City_Original_environment) + (0+lme4::dummy(Generation, "G2")|City_Original_environment), data=data[data$Test_environment=="Strawberry",], REML = FALSE)

m01 <- lme4::lmer(log(Nb_eggs+1)  ~ BoxID + (0+Generation | City_Original_environment) , data=data[data$Test_environment=="Strawberry",], REML = TRUE)

MuMIn::model.sel(m00, m01)

## Cherry
m00 <- lme4::lmer(log(Nb_eggs+1)  ~ BoxID + (0+ lme4::dummy(Generation, "G0") |  City_Original_environment) + (0+lme4::dummy(Generation, "G2")|City_Original_environment), data=data[data$Test_environment=="Cherry",], REML = FALSE)

m01 <- lme4::lmer(log(Nb_eggs+1)  ~ BoxID + (0+Generation | City_Original_environment) , data=data[data$Test_environment=="Cherry",], REML = TRUE)

MuMIn::model.sel(m00, m01)

##Cl:Performance in G0 and G2 are not correlated

```

## Accounting for differences among original environments in G0
### Plot
```{r }

head(data)
title_plot <- "CorrelationsG0_G2_EmergenceRateLaureG0differences.pdf"
modelformula <- asin(sqrt(Emergence_Rate))  ~ Original_environment*Generation + Test_environment + log(Nb_eggscorrected)
#modelformula <- log(Nb_adults+1)  ~ Test_environment + log(Nb_eggscorrected+1)

## Create new variable
data$City_Original_environment <- as.factor(paste(data$City, data$Original_environment, sep="_"))
head(data)

## Select the datasets to use for the graph
dataselect <- !is.na(data$Emergence_Rate)
#dataselect <- !is.na(data$Nb_adults)&!is.na(data$Nb_eggscorrected)

###PLOT 
(PAIR_G0_G2 <- plot_correlation_meanresiduals(dataset = data[dataselect,], formula=modelformula, envfactor="Generation", additional_factor="Test_environment", original_environment="Original_environment", col_original_environment= c("#301934","#BC3C6D", "#3FAA96"), grp_cols=c("City_Original_environment", "Original_environment", "Test_environment", "Generation"), facetwrap=TRUE, fixedxylim = FALSE, bisector = TRUE, xaxis_labelprint = "Performance G1", yaxis_labelprint =  "Performance G3"))

(PAIR_G0_G2_label <- plot_correlation_meanresiduals(dataset = data[dataselect,], formula=modelformula, envfactor="Generation", additional_factor="Test_environment", original_environment="Original_environment", col_original_environment= c("#301934","#BC3C6D", "#3FAA96"), grp_cols=c("City_Original_environment", "Original_environment", "Test_environment", "Generation"), facetwrap=TRUE, printnames=TRUE, printsamplesize=TRUE, fixedxylim = FALSE, bisector = TRUE, xaxis_labelprint = "Performance G1", yaxis_labelprint =  "Performance G3"))

figure <- ggpubr::ggarrange(PAIR_G0_G2, PAIR_G0_G2_label,
                    labels = c("A", "B"),
                    ncol = 1, nrow = 2, common.legend = TRUE, legend = "bottom")

cowplot::save_plot(file =here::here("plots", title_plot),
                 figure, base_height = 20/cm(1),
                  base_width = 20/cm(1), dpi = 1200)


```

### Analyses of Emergence rate
```{r }
## Create new variable
data$City_Original_environment <- as.factor(paste(data$City, data$Original_environment, sep="_"))

## Blackberry
m00 <- lme4::lmer(asin(sqrt(Emergence_Rate))  ~ Generation*Original_environment+log(Nb_eggscorrected) + (0+ lme4::dummy(Generation, "G0") |  City_Original_environment) + (0+lme4::dummy(Generation, "G2")|City_Original_environment), data=data[data$Test_environment=="Blackberry"&!is.na(data$Emergence_Rate),], REML = TRUE)

m01 <- lme4::lmer(asin(sqrt(Emergence_Rate))  ~ Generation*Original_environment+log(Nb_eggscorrected) + (0+Generation | City_Original_environment), data=data[data$Test_environment=="Blackberry"&!is.na(data$Emergence_Rate),], REML = TRUE)

summary(m00)
summary(m01)
MuMIn::model.sel(m00, m01)

## Strawberry
m00 <- lme4::lmer(asin(sqrt(Emergence_Rate))  ~ Generation*Original_environment+log(Nb_eggscorrected) + (0+ lme4::dummy(Generation, "G0")| City_Original_environment) + (0+lme4::dummy(Generation, "G2")|City_Original_environment), data=data[data$Test_environment=="Strawberry"&!is.na(data$Emergence_Rate),], REML = TRUE)
m01 <- lme4::lmer(asin(sqrt(Emergence_Rate))  ~ Generation*Original_environment+log(Nb_eggscorrected) + (0+Generation|City_Original_environment) , data=data[data$Test_environment=="Strawberry"&!is.na(data$Emergence_Rate),], REML = TRUE)
MuMIn::model.sel(m00, m01)

## Cherry
m00 <- lme4::lmer(asin(sqrt(Emergence_Rate))  ~ Generation*Original_environment+log(Nb_eggscorrected) + (0+ lme4::dummy(Generation, "G0")| City_Original_environment) + (0+lme4::dummy(Generation, "G2")|City_Original_environment), data=data[data$Test_environment=="Cherry"&!is.na(data$Emergence_Rate),], REML = TRUE)
m01 <- lme4::lmer(asin(sqrt(Emergence_Rate))  ~ Generation*Original_environment+log(Nb_eggscorrected)+ (0+Generation|City_Original_environment) , data=data[data$Test_environment=="Cherry"&!is.na(data$Emergence_Rate),], REML = TRUE)
MuMIn::model.sel(m00, m01)

##Cl:Performance in G0 and G2 are not correlated

```
