---
title: "Power test: detection non genetic local adaptation"
author: "Laure Olazcuaga, Nicolas Rode"
date: "`r format(Sys.Date(), '%d-%B-%Y')`"
output: 
  html_document:
    theme: "journal"
    toc: true
    toc_depth: 3
    number_sections: true
    toc_float:
      collapsed: false
      smooth_scroll: false
editor_options: 
  chunk_output_type: console
---


```{r setup, include =FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
devtools::load_all()
```

#NUMBER OF SIMULS
```{r } 
nb_simul <- 1000
```



# DATA 
```{r }
#############################
#PERFORMANCE 
#############################

data_PERF <- import_data(dataset = "DATACOMPLET_PERF.csv", 
                         trait = "performance",
                         remove_testenvt = c("Grape","GF"), 
                         remove_pop = c("WT3"), 
                         remove_rate = NA)

tapply(data_PERF$Nb_adults,list(data_PERF$Original_environment,data_PERF$Generation),length)

#############################
#EMERGENCE RATE
#############################

data_PERF_Rate <- import_data(dataset = "DATACOMPLET_PERF.csv", 
                         trait = "performance",
                         remove_testenvt = c("Grape","GF"), 
                         remove_pop = c("WT3"), 
                         remove_rate = TRUE)


###########################
#PREFERENCE 
###########################
data_PREF <- import_data(dataset = "DATACOMPLET_PREF.csv", 
                         trait = "preference",
                         remove_testenvt = NA, 
                         remove_pop = c("WT3"), 
                         remove_rate = NA)

head(data_PREF)
tapply(data_PREF$Nb_eggs,list(data_PREF$Original_environment,data_PREF$Generation),length)



###########################
#PREFERENCE 3 fruits
###########################
levels_test<-levels(data_PREF$Test_environment)
levels_original<-levels(data_PREF$Original_environment)


data_PREF_three <- import_data(dataset = "DATACOMPLET_PREF.csv", 
                         trait = "preference",
                         remove_testenvt = usefun::outersect(levels_test, 
                                                             levels_original), 
                         remove_pop = c("WT3"), 
                         remove_rate = NA)

head(data_PREF_three)
tapply(data_PREF_three$Nb_eggs,list(data_PREF_three$Original_environment,
                                    data_PREF_three$Generation),length)



dim(data_PREF_three)
dim(data_PREF)



```


# Preliminary check of the function
```{r }
#Check: 
sim <- sapply(1:1000, simul_powertest_nongenet, SAng= 0.032,  dup = 1)
sim <- as.data.frame(t(sim))

#SA genet
mean(sim$SAGen)
mean(sim$SAGen_Est)

#SA Non genet
mean(sim$SANonGen)
mean(sim$SANonGen_Est)

#SA and SAnon genet estimated with simulated data are similar to the SA and SAnon genet estimated with real data

#Proportion of simuls where tests are significant:
mean(sim$IndicGen)
mean(sim$IndicNonGen)

```


# POWER TEST
```{r }
#### INCREASE SA NON GENETIC
nb_simul = 1000
val_SAng <- seq(from = 0, to = 1, by = 0.1)


#Table with all combination seed x SAng tested
val_simul<-c(1:nb_simul)
value_param <- expand.grid("val_SAng" = val_SAng,
                           "val_simul" = val_simul, 
                           "val_duplication" = c(1))

#mapply to perform several seed and several SAng
sim <- mapply(simul_powertest_nongenet, 
              seed = value_param$val_simul, 
              SAng = value_param$val_SAng, 
              dup = value_param$val_duplication)
sim <- as.data.frame(t(as.data.frame(sim)))


#Dataset proportion
TEMP <- as.data.frame(tapply(sim$IndicNonGen, list(sim$SAng,sim$dup), mean))
TEMP$val_SAng <- rownames(TEMP)
data_prop <- tidyr::gather(TEMP, "duplication", "prop_nongen_sign", 1:dim(TEMP)[2]-1)
data_prop$duplication <- factor(data_prop$duplication, levels = c("1"))


#Plot des simuls
power_test_simple <- ggplot2::ggplot(data = data_prop, 
                              aes(x = val_SAng, 
                                  y = prop_nongen_sign)) + 
  geom_point(size = 3) + 
  geom_line(size = 1) + 
  geom_vline(xintercept = 0.03152, linetype = "dashed", color = "red", size = 0.5) + 
  ylab("Proportion of simulations with\nsignificant adaptive phenotypic plasticity")  +
  xlab("Intensity of SA plastic")  +
  ggtitle("Egg-to-adult viability")  +
  ylim(0,1) +
  theme_LO_sober  
power_test_simple


  
name_plot<-paste0("Simul_powertest_nongeneticdetection_",
      nb_simul,"nbsimulperSAng.pdf")
# cowplot::save_plot(file =here::here("figures",name_plot ),
#                   power_test, base_height = 14/cm(1),
#                   base_width = 20/cm(1), dpi = 1200)




#### DUPLICATION DATASET
nb_simul = 1000
val_SAng <- seq(from = 0, to = 1, by = 0.1)


#Table with all combination seed x SAng tested
val_simul<-c(1:nb_simul)
value_param <- expand.grid("val_SAng" = val_SAng,
                           "val_simul" = val_simul, 
                           "val_duplication" = c(1,2,10,100))

#mapply to perform several seed and several SAng
sim <- mapply(simul_powertest_nongenet, 
              seed = value_param$val_simul, 
              SAng = value_param$val_SAng, 
              dup = value_param$val_duplication)
sim <- as.data.frame(t(as.data.frame(sim)))


#Dataset proportion
TEMP <- as.data.frame(tapply(sim$IndicNonGen, list(sim$SAng,sim$dup), mean))
TEMP$val_SAng <- rownames(TEMP)
data_prop <- tidyr::gather(TEMP, "duplication", "prop_nongen_sign", 1:dim(TEMP)[2]-1)
data_prop$duplication <- factor(data_prop$duplication, levels = c("1","2","10","100"))


data_prop$val_SAng <- as.numeric(data_prop$val_SAng)

#Plot des simuls
power_test <- ggplot2::ggplot(data = data_prop, 
                              aes(x = val_SAng, 
                                  y = prop_nongen_sign,
                                  group = duplication,
                                  color = duplication)) + 
  geom_point(size = 3) + 
  geom_line(size = 1) + 
  geom_hline(yintercept = 0.8, linetype = "dashed", color = "grey", size = 0.5) + 
  ylab("Proportion of simulations with\nsignificant adaptive phenotypic plasticity")  +
  xlab("Intensity of SA plastic")  +
  ggtitle("Egg-to-adult viability")  +
  labs(color = "Size of the design\nrelative to our\noriginal design") +
  scale_color_manual(values=c("#D36582","#a1dab4","#41b6c4","#225ea8"),
                     breaks=c("1","2","10","100"),
                    labels=c("X1","X2","X10","X100"))+
  ylim(0,1) +
  xlim(0,1) +
  theme_LO_sober  
power_test


  
name_plot<-paste0("Simul_powertest_nongeneticdetection_",
      nb_simul,"nbsimulperSAng.pdf")
# cowplot::save_plot(file =here::here("figures",name_plot ),
#                   power_test, base_height = 14/cm(1),
#                   base_width = 20/cm(1), dpi = 1200)




```


# Extract value of power
```{r }
#To calculate more precisely when we can detect SAnon genet
data_prop[data_prop$duplication=="1",]
power_test

#In our simul we can detect with a value of SAnongent between 0.4 and 0.5
##Simul with more precision between 0.4 and 0.5
val_SAng <- seq(from = 0.44, to = 0.48, by = 0.01)
val_simul<-c(1:nb_simul)
value_param <- expand.grid("val_SAng" = val_SAng,
                           "val_simul" = val_simul, 
                           "val_duplication" = c(1))
sim <- mapply(simul_powertest_nongenet, 
              seed = value_param$val_simul, 
              SAng = value_param$val_SAng, 
              dup = value_param$val_duplication)
sim <- as.data.frame(t(as.data.frame(sim)))
TEMP <- as.data.frame(tapply(sim$IndicNonGen, list(sim$SAng,sim$dup), mean))
TEMP$val_SAng <- rownames(TEMP)
data_prop <- tidyr::gather(TEMP, "duplication", "prop_nongen_sign", 1:dim(TEMP)[2]-1)
data_prop$val_SAng <- as.numeric(data_prop$val_SAng)
data_prop <- data.frame(val_SAng = val_SAng, 
                 prop_nongen_sign = tapply(sim$IndicNonGen[sim$dup==1], 
                                        sim$SAng[sim$dup==1], mean), 
                 rsqng = tapply(sim$rsqng[sim$dup==1], 
                                         sim$SAng[sim$dup==1], mean))


data_prop


```



# Check problem of SAgenetic with SA non genetic
```{r }
################# 
################# PROBLEM GENETIC VS NON GENETIC
################# 
data_prop <- data.frame(val_SAng = val_SAng, 
                 prop_gen_sign = tapply(sim$IndicGen[sim$dup==1], 
                                        sim$SAng[sim$dup==1], mean), 
                 prop_nongen_sign = tapply(sim$IndicNonGen[sim$dup==1], 
                                         sim$SAng[sim$dup==1], mean))


colors <- c("Genetic" = "red", "Non-genetic" = "black")
#Plot des simuls
power_test <- ggplot2::ggplot(data = data_prop, aes(x=val_SAng)) + 
  geom_point(aes(y = prop_nongen_sign, color="Non-genetic"), size = 3) + 
  geom_line(aes(y = prop_nongen_sign, color="Non-genetic"), size = 1) + 
  geom_point(aes(y = prop_gen_sign, color="Genetic"), size = 3) + 
  geom_line(aes(y = prop_gen_sign, color="Genetic"), size = 1) + 
  geom_vline(xintercept = 0.03152, linetype = "dashed", color = "red", size = 0.5) + 
  ylab("Proportion of simulations with\nsignificant adaptive phenotypic plasticity")  +
  xlab("Intensity of SA plastic")  +
  ggtitle("Egg-to-adult survival")  +
  labs(color = "Power test") +
  scale_color_manual(values = colors) +
  ylim(0,1) +
  theme_LO_sober  
power_test

name_plot<-paste0("Simul_powertest_nongeneticdetection_vs_geneticdetection",
      nb_simul,"nbsimulperSAng.pdf")
# cowplot::save_plot(file =here::here("figures",name_plot ),
#                   power_test, base_height = 14/cm(1),
#                   base_width = 20/cm(1), dpi = 1200)
# 

```


