---
title: "Correlation between generations"
author: "Laure Olazcuaga, Nicolas Rode"
date: "`r format(Sys.Date(), '%d-%B-%Y')`"
output: 
  html_document:
    theme: "journal"
    toc: true
    toc_depth: 3
    number_sections: true
    toc_float:
      collapsed: false
      smooth_scroll: false
editor_options: 
  chunk_output_type: console
---


```{r setup, include =FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
devtools::load_all()
```


# DATA 
```{r }
#############################
#PERFORMANCE 
#############################

data_PERF <- import_data(dataset = "DATACOMPLET_PERF.csv", 
                         trait = "performance",
                         remove_testenvt = c("Grape","GF"), 
                         remove_pop = c("WT3"), 
                         remove_rate = NA)

head(data_PERF)
tapply(data_PERF$Nb_adults,list(data_PERF$Original_environment,data_PERF$Generation),length)

#############################
#EMERGENCE RATE
#############################

data_PERF_Rate <- import_data(dataset = "DATACOMPLET_PERF.csv", 
                         trait = "performance",
                         remove_testenvt = c("Grape","GF"), 
                         remove_pop = c("WT3"), 
                         remove_rate = TRUE)
head(data_PERF_Rate)
tapply(data_PERF_Rate$Nb_adults,list(data_PERF_Rate$Original_environment,
                                     data_PERF_Rate$Generation),length)

tapply(data_PERF_Rate$Rate,data_PERF_Rate$Generation,mean)

## To test Rate higher than 1
# data_PERF_Rate <- import_data(dataset = "DATACOMPLET_PERF.csv", 
#                          trait = "performance",
#                          remove_testenvt = c("Grape","GF"), 
#                          remove_pop = c("WT3"), 
#                          remove_rate = NA)
# #Replace Rate>1 by 1
# data_PERF_Rate$Rate[data_PERF_Rate$Nb_adults>=data_PERF_Rate$Nb_eggs] <- 1

###########################
#PREFERENCE 
###########################
data_PREF <- import_data(dataset = "DATACOMPLET_PREF.csv", 
                         trait = "preference",
                         remove_testenvt = NA, 
                         remove_pop = c("WT3"), 
                         remove_rate = NA)

head(data_PREF)
tapply(data_PREF$Nb_eggs,list(data_PREF$Original_environment,data_PREF$Generation),length)



###########################
#PREFERENCE 3 fruits
###########################
levels_test<-levels(data_PREF$Test_environment)
levels_original<-levels(data_PREF$Original_environment)


data_PREF_three <- import_data(dataset = "DATACOMPLET_PREF.csv", 
                         trait = "preference",
                         remove_testenvt = usefun::outersect(levels_test, 
                                                             levels_original), 
                         remove_pop = c("WT3"), 
                         remove_rate = NA)

head(data_PREF_three)
tapply(data_PREF_three$Nb_eggs,list(data_PREF_three$Original_environment,
                                    data_PREF_three$Generation),length)

resume_design<-tapply(as.factor(data_PREF_three$BoxID),list(data_PREF_three$Population,
                                  data_PREF_three$Generation),length)
mean(resume_design[,1], na.rm = TRUE)/3
mean(resume_design[,2], na.rm = TRUE)/3

resume_design<-tapply(data_PERF$Nb_eggs,list(data_PERF$Population,
                                  data_PERF$Generation),length)
mean(resume_design[,1], na.rm = TRUE)/3
mean(resume_design[,2], na.rm = TRUE)/3

dim(data_PREF_three)
dim(data_PREF)
head(data_PREF)


levels(data_PREF$Population)
```

# Preference vs. Stimulation 
```{r }

# G0 
pref_stim_G0 <- plot_CorrelationTraits_residuals(gen = "G0", fruit = "All",
                                 dataset1 = data_PERF,
                                 dataset2 = data_PREF_three,
                                 formula1 = "log(Nb_eggs+1) ~ Test_environment + Population",
                                 formula2 = "log(Nb_eggs+1) ~ Test_environment + Population + BoxID",
                                 axis_label_trait1 = "Oviposition stimulation",
                                 axis_label_trait2 = "Oviposition preference",
                                 subscript_label = "preference/stimulation in G0", 
                                 printcor=TRUE)


# G2 
pref_stim_G2 <- plot_CorrelationTraits_residuals(gen = "G2", fruit = "All",
                                 dataset1 = data_PERF,
                                 dataset2 = data_PREF_three,
                                 formula1 = "log(Nb_eggs+1) ~ Test_environment + Population",
                                 formula2 = "log(Nb_eggs+1) ~ Test_environment + Population + BoxID",
                                 axis_label_trait1 = "Oviposition stimulation",
                                 axis_label_trait2 = "Oviposition preference",
                                 subscript_label = "preference/stimulation in G2", 
                                 printcor=TRUE)



```



# Preference vs. Performance 
```{r }

# G0 
MKB_G0 <- plot_CorrelationTraits_residuals(gen = "G0", fruit = "All",
                                 dataset1 = data_PERF_Rate,
                                 dataset2 = data_PREF_three,
                                 formula1 = "asin(sqrt(Rate)) ~ Test_environment + Population + log(Nb_eggs)",
                                 formula2 = "log(Nb_eggs+1) ~ Test_environment + Population + BoxID",
                                 axis_label_trait1 = "Offspring performance",
                                 axis_label_trait2 = "Oviposition preference",
                                 subscript_label = "Preference G0/Performance G1", 
                                 printcor=TRUE)


# G2 
MKB_G2 <- plot_CorrelationTraits_residuals(gen = "G2", fruit = "All",
                                 dataset1 = data_PERF_Rate,
                                 dataset2 = data_PREF_three,
                                 formula1 = "asin(sqrt(Rate)) ~ Test_environment + Population + log(Nb_eggs)",
                                 formula2 = "log(Nb_eggs+1) ~ Test_environment + Population + BoxID",
                                 axis_label_trait1 = "Offspring performance",
                                 axis_label_trait2 = "Oviposition preference",
                                 subscript_label = "Preference G2/Performance G3", 
                                 printcor=TRUE)


legend <- lemon::g_legend(MKB_G2)


## ALL GENERATIONS 
MotherKnowsBest_G0G2 <- cowplot::ggdraw() + 
  cowplot::draw_plot(MKB_G0 + theme(legend.position = "none", 
                                        plot.title = element_blank()), 
            x = 0.01, y = 0.5, width = 0.75, height = 0.43) + 
  cowplot::draw_plot(MKB_G2 + theme(legend.position = "none", 
                                        plot.title = element_blank()), 
            x = 0.01, y = 0, width = 0.75, height = 0.43) + 
  cowplot::draw_plot(legend, x = 0.87, y = 0.5, width = 0.00001, height = 0.00001) + 
  cowplot::draw_plot_label(c("Generation: G0/G1", "A", "Generation: G2/G3", "B"),  
                  x = c(0.33, 0.01, 0.33, 0.01), 
                  y = c(0.97, 0.97,  0.47, 0.47), 
                  hjust = c(0,0,0,0), 
                  vjust = c(1.5, 1.5, 1.5, 1.5),
                  size = 14) 
 MotherKnowsBest_G0G2
 
 

 cowplot::save_plot(file =here::here("figures", "Supplements_FigS8_MotherKnowsBest.pdf"),
                   MotherKnowsBest_G0G2,
                   base_height = 22/cm(1), base_width = 14/cm(1), dpi = 610)



 
 
```



# PLOT
```{r }

PLOT_Blackberry <- plot_RelationTraits_residuals(gen = "G2", 
                                                fruit = "Blackberry", 
                                                trait2 = "Preference")
PLOT_Cherry <- plot_RelationTraits_residuals(gen = "G2", 
                                                fruit = "Cherry", 
                                                trait2 = "Preference")
PLOT_Strawberry <- plot_RelationTraits_residuals(gen = "G2", 
                                                fruit = "Strawberry", 
                                                trait2 = "Preference")

PLOT_Blackberry_G0 <- plot_RelationTraits_residuals(gen = "G0", 
                                                fruit = "Blackberry", 
                                                trait2 = "Preference")
PLOT_Cherry_G0 <- plot_RelationTraits_residuals(gen = "G0", 
                                                fruit = "Cherry", 
                                                trait2 = "Preference")
PLOT_Strawberry_G0 <- plot_RelationTraits_residuals(gen = "G0", 
                                                fruit = "Strawberry", 
                                                trait2 = "Preference")

legend <- lemon::g_legend(PLOT_Strawberry_G0)



## ALL GENERATIONS 
 RELATION_TRAITS_G0G2 <- cowplot::ggdraw() + 
  cowplot::draw_plot(PLOT_Blackberry_G0 + theme(legend.position = "none", 
                                        plot.title = element_blank()), 
            x = 0.01, y = 0.5, width = 0.24, height = 0.43) + 
  cowplot::draw_plot(PLOT_Cherry_G0 + theme(legend.position = "none", 
                                        plot.title = element_blank()), 
            x = 0.31, y = 0.5, width = 0.24, height = 0.43) + 
  cowplot::draw_plot(PLOT_Strawberry_G0 + theme(legend.position = "none", 
                                        plot.title = element_blank()), 
            x = 0.61, y = 0.5, width = 0.24, height = 0.43) + 
  cowplot::draw_plot(legend, x = 0.93, y = 0.5, width = 0.0001, height = 0.0001) + 
  cowplot::draw_plot(PLOT_Blackberry + theme(legend.position = "none", 
                                        plot.title = element_blank()), 
            x = 0.01, y = 0, width = 0.24, height = 0.43) + 
  cowplot::draw_plot(PLOT_Cherry + theme(legend.position = "none", 
                                        plot.title = element_blank()), 
            x = 0.31, y = 0, width = 0.24, height = 0.43) + 
  cowplot::draw_plot(PLOT_Strawberry + theme(legend.position = "none", 
                                        plot.title = element_blank()), 
            x = 0.61, y = 0, width = 0.24, height = 0.43) + 
  cowplot::draw_plot_label(c("Generation: G0/G1", "A", "B", "C", " ",
                    "Generation: G2/G3", "D", "E", "F", " "),  
                  x = c(0.4, 0.01, 0.30, 0.61, 0.92, 0.4, 0.01, 0.3, 0.61, 0.92), 
                  y = c(1, 0.98, 0.98, 0.98, 0.98, 0.5, 0.48, 0.48, 0.48, 0.48), 
                  hjust = c(0,0,0,0,0,0,0,0,0,0), 
                  vjust = c(1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5),
                  size = 16) 
 RELATION_TRAITS_G0G2
 

# 
# cowplot::save_plot(file =here::here("figures", "Supplements_MotherKnowsBest_Preference_fruitpairs.pdf"),
#                   RELATION_TRAITS_G0G2,
#                   base_height = 18/cm(1), base_width = 34/cm(1), dpi = 610)
# 



##### With stimulation 
 PLOT_Blackberry_Stim <- plot_RelationTraits_residuals(gen = "G2", 
                                                fruit = "Blackberry", 
                                                trait2 = "Stimulation")
PLOT_Cherry_Stim <- plot_RelationTraits_residuals(gen = "G2", 
                                                fruit = "Cherry", 
                                                trait2 = "Stimulation")
PLOT_Strawberry_Stim <- plot_RelationTraits_residuals(gen = "G2", 
                                                fruit = "Strawberry", 
                                                trait2 = "Stimulation")
PLOT_Blackberry_Stim_G0 <- plot_RelationTraits_residuals(gen = "G0", 
                                                fruit = "Blackberry", 
                                                trait2 = "Stimulation")
PLOT_Cherry_Stim_G0 <- plot_RelationTraits_residuals(gen = "G0", 
                                                fruit = "Cherry", 
                                                trait2 = "Stimulation")
PLOT_Strawberry_Stim_G0 <- plot_RelationTraits_residuals(gen = "G0", 
                                                fruit = "Strawberry", 
                                                trait2 = "Stimulation")
 
 
 ## ALL GENERATIONS 
 RELATION_TRAITS_Stimulation_G0G2 <- cowplot::ggdraw() + 
  cowplot::draw_plot(PLOT_Blackberry_Stim_G0 + theme(legend.position = "none", 
                                        plot.title = element_blank()), 
            x = 0.01, y = 0.5, width = 0.24, height = 0.43) + 
  cowplot::draw_plot(PLOT_Cherry_Stim_G0 + theme(legend.position = "none", 
                                        plot.title = element_blank()), 
            x = 0.31, y = 0.5, width = 0.24, height = 0.43) + 
  cowplot::draw_plot(PLOT_Strawberry_Stim_G0 + theme(legend.position = "none", 
                                        plot.title = element_blank()), 
            x = 0.61, y = 0.5, width = 0.24, height = 0.43) + 
  cowplot::draw_plot(legend, x = 0.93, y = 0.5, width = 0.0001, height = 0.0001) + 
  cowplot::draw_plot(PLOT_Blackberry_Stim + theme(legend.position = "none", 
                                        plot.title = element_blank()), 
            x = 0.01, y = 0, width = 0.24, height = 0.43) + 
  cowplot::draw_plot(PLOT_Cherry_Stim + theme(legend.position = "none", 
                                        plot.title = element_blank()), 
            x = 0.31, y = 0, width = 0.24, height = 0.43) + 
  cowplot::draw_plot(PLOT_Strawberry_Stim + theme(legend.position = "none", 
                                        plot.title = element_blank()), 
            x = 0.61, y = 0, width = 0.24, height = 0.43) + 
  cowplot::draw_plot_label(c("Generation: G0/G1", "A", "B", "C", " ",
                    "Generation: G2/G3", "D", "E", "F", " "),  
                  x = c(0.4, 0.01, 0.30, 0.61, 0.92, 0.4, 0.01, 0.3, 0.61, 0.92), 
                  y = c(1, 0.98, 0.98, 0.98, 0.98, 0.5, 0.48, 0.48, 0.48, 0.48), 
                  hjust = c(0,0,0,0,0,0,0,0,0,0), 
                  vjust = c(1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5),
                  size = 16) 
 RELATION_TRAITS_Stimulation_G0G2
# 
# 
# cowplot::save_plot(file =here::here("figures", "Supplements_MotherKnowsBest_Stimulation_fruitpairs.pdf"),
#                   RELATION_TRAITS_Stimulation_G0G2,
#                   base_height = 18/cm(1), base_width = 34/cm(1), dpi = 610)

```

