---
title: "Heterogeneity across populations"
author: "Laure Olazcuaga, Nicolas Rode"
date: "`r format(Sys.Date(), '%d-%B-%Y')`"
output: 
  html_document:
    theme: "journal"
    toc: true
    toc_depth: 3
    number_sections: true
    toc_float:
      collapsed: false
      smooth_scroll: false
editor_options: 
  chunk_output_type: console
---


```{r setup, include =FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
devtools::load_all()
```


# DATA 
```{r }
#############################
#PERFORMANCE 
#############################

data_PERF <- import_data(dataset = "DATACOMPLET_PERF.csv", 
                         trait = "performance",
                         remove_testenvt = c("Grape","GF"), 
                         remove_pop = c("WT3"), 
                         remove_rate = NA)

head(data_PERF)
tapply(data_PERF$Nb_adults,list(data_PERF$Original_environment,data_PERF$Generation),length)


#############################
#EMERGENCE RATE
#############################

data_PERF_Rate <- import_data(dataset = "DATACOMPLET_PERF.csv", 
                         trait = "performance",
                         remove_testenvt = c("Grape","GF"), 
                         remove_pop = c("WT3"), 
                         remove_rate = "Replace")
head(data_PERF_Rate)
tapply(data_PERF_Rate$Nb_adults,list(data_PERF_Rate$Original_environment,
                                     data_PERF_Rate$Generation),length)

tapply(data_PERF_Rate$Rate,data_PERF_Rate$Generation,mean)



###########################
#PREFERENCE 
###########################
data_PREF <- import_data(dataset = "DATACOMPLET_PREF.csv", 
                         trait = "preference",
                         remove_testenvt = NA, 
                         remove_pop = c("WT3"), 
                         remove_rate = NA)

head(data_PREF)
tapply(data_PREF$Nb_eggs,list(data_PREF$Original_environment,data_PREF$Generation),length)


###########################
#PREFERENCE 3 fruits
###########################
levels_test<-levels(data_PREF$Test_environment)
levels_original<-levels(data_PREF$Original_environment)


data_PREF_three <- import_data(dataset = "DATACOMPLET_PREF.csv", 
                         trait = "preference",
                         remove_testenvt = usefun::outersect(levels_test, 
                                                             levels_original), 
                         remove_pop = c("WT3"), 
                         remove_rate = NA)

head(data_PREF_three)
tapply(data_PREF_three$Nb_eggs,list(data_PREF_three$Original_environment,
                                    data_PREF_three$Generation),length)

resume_design<-tapply(as.factor(data_PREF_three$BoxID),list(data_PREF_three$Population,
                                  data_PREF_three$Generation),length)
mean(resume_design[,1], na.rm = TRUE)/3
mean(resume_design[,2], na.rm = TRUE)/3

resume_design<-tapply(data_PERF$Nb_eggs,list(data_PERF$Population,
                                  data_PERF$Generation),length)
mean(resume_design[,1], na.rm = TRUE)/3
mean(resume_design[,2], na.rm = TRUE)/3

dim(data_PREF_three)
dim(data_PREF)
head(data_PREF)


levels(data_PREF$Population)
```

## Plot
```{r }
HA_Rate_G0 <- plot_pop_homeaway(dataset = data_PERF_Rate, 
         gen = "G0",  trait="Rate",
         yaxis_labelprint = "Difference in offspring performance\nbetween original and alternative fruits")
HA_Rate_G2 <- plot_pop_homeaway(dataset = data_PERF_Rate,
         gen = "G2", trait="Rate",
         yaxis_labelprint = "Difference in offspring performance\nbetween original and alternative fruits")


HA_pref_G0 <- plot_pop_homeaway(dataset = data_PREF_three,
         gen = "G0", trait="Nb_eggs",
         yaxis_labelprint = "Difference in oviposition preference\nbetween original and alternative fruits")
HA_pref_G2 <- plot_pop_homeaway(dataset = data_PREF_three,
         gen = "G2", trait="Nb_eggs",
         yaxis_labelprint = "Difference in oviposition preference\nbetween original and alternative fruits")

HA_stim_G0 <- plot_pop_homeaway(dataset = data_PERF,
         gen = "G0", trait="Nb_eggs",
         yaxis_labelprint = "Difference in fecundity between\noriginal and alternative fruits")
HA_stim_G2 <- plot_pop_homeaway(dataset = data_PERF,
         gen = "G2", trait="Nb_eggs",
         yaxis_labelprint = "Difference in fecundity between\noriginal and alternative fruits")



legend <- lemon::g_legend(HA_stim_G2)

 
## ALL GENERATIONS 
HomeAway_Figure_ALL <- cowplot::ggdraw() + 
  cowplot::draw_plot(HA_pref_G0 + theme(legend.position = "none", 
                                        plot.title = element_blank()), 
            x = 0.0, y = 0.66, width = 0.4, height = 0.3) + 
  cowplot::draw_plot(HA_stim_G0 + theme(legend.position = "none", 
                                        plot.title = element_blank()), 
            x = 0.0, y = 0.33, width = 0.4, height = 0.3) + 
  cowplot::draw_plot(HA_Rate_G0 + theme(legend.position = "none", 
                                        plot.title = element_blank()), 
            x = 0.01, y = 0, width = 0.4, height = 0.3) + 
  cowplot::draw_plot(HA_pref_G2 + theme(legend.position = "none", 
                                        plot.title = element_blank()), 
            x = 0.44, y = 0.66, width = 0.4, height = 0.3) + 
  cowplot::draw_plot(HA_stim_G2 + theme(legend.position = "none", 
                                        plot.title = element_blank()), 
            x = 0.44, y = 0.33, width = 0.4, height = 0.3) + 
  cowplot::draw_plot(HA_Rate_G2 + theme(legend.position = "none", 
                                        plot.title = element_blank()), 
            x = 0.44, y = 0, width = 0.4, height = 0.3) + 
  cowplot::draw_plot(legend, x = 0.915, y = 0.5, width = 0.000001, height = 0.000001) + 
  cowplot::draw_plot_label(c("Generation G0/G1","Generation G2/G3","A", "B", "C",
                    "D", "E", "F"),  
                  x = c(0.12,0.55, 0, 0.44, 0, 0.44, 0, 0.44 ), 
                  y = c(1,1, 0.99, 0.99, 0.66,  0.66, 0.33, 0.33), 
                  hjust = c(0,0,0,0,0,0,0,0), 
                  vjust = c(1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5),
                  size = 18) 

cowplot::save_plot(file =here::here("figures", "FigSX_HomeAwayTest.pdf"),
                  HomeAway_Figure_ALL,
                  base_height = 36/cm(1), base_width = 28/cm(1), dpi = 610)






```


