---
title: "Correlation between generations"
author: "Laure Olazcuaga, Nicolas Rode"
date: "`r format(Sys.Date(), '%d-%B-%Y')`"
output: 
  html_document:
    theme: "journal"
    toc: true
    toc_depth: 3
    number_sections: true
    toc_float:
      collapsed: false
      smooth_scroll: false
editor_options: 
  chunk_output_type: console
---


```{r setup, include =FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
devtools::load_all()
```


# DATA 
```{r }
#############################
#PERFORMANCE 
#############################

data_PERF <- import_data(dataset = "DATACOMPLET_PERF.csv", 
                         trait = "performance",
                         remove_testenvt = c("Grape","GF"), 
                         remove_pop = c("WT3"), 
                         remove_rate = NA)

head(data_PERF)
tapply(data_PERF$Nb_adults,list(data_PERF$Original_environment,data_PERF$Generation),length)

#############################
#EMERGENCE RATE
#############################

data_PERF_Rate <- import_data(dataset = "DATACOMPLET_PERF.csv", 
                         trait = "performance",
                         remove_testenvt = c("Grape","GF"), 
                         remove_pop = c("WT3"), 
                         remove_rate = TRUE)
head(data_PERF_Rate)
tapply(data_PERF_Rate$Nb_adults,list(data_PERF_Rate$Original_environment,
                                     data_PERF_Rate$Generation),length)

tapply(data_PERF_Rate$Rate,data_PERF_Rate$Generation,mean)

## To test Rate higher than 1
# data_PERF_Rate <- import_data(dataset = "DATACOMPLET_PERF.csv", 
#                          trait = "performance",
#                          remove_testenvt = c("Grape","GF"), 
#                          remove_pop = c("WT3"), 
#                          remove_rate = NA)
# #Replace Rate>1 by 1
# data_PERF_Rate$Rate[data_PERF_Rate$Nb_adults>=data_PERF_Rate$Nb_eggs] <- 1

###########################
#PREFERENCE 
###########################
data_PREF <- import_data(dataset = "DATACOMPLET_PREF.csv", 
                         trait = "preference",
                         remove_testenvt = NA, 
                         remove_pop = c("WT3"), 
                         remove_rate = NA)

head(data_PREF)
tapply(data_PREF$Nb_eggs,list(data_PREF$Original_environment,data_PREF$Generation),length)



###########################
#PREFERENCE 3 fruits
###########################
levels_test<-levels(data_PREF$Test_environment)
levels_original<-levels(data_PREF$Original_environment)


data_PREF_three <- import_data(dataset = "DATACOMPLET_PREF.csv", 
                         trait = "preference",
                         remove_testenvt = usefun::outersect(levels_test, 
                                                             levels_original), 
                         remove_pop = c("WT3"), 
                         remove_rate = NA)

head(data_PREF_three)
tapply(data_PREF_three$Nb_eggs,list(data_PREF_three$Original_environment,
                                    data_PREF_three$Generation),length)

resume_design<-tapply(as.factor(data_PREF_three$BoxID),list(data_PREF_three$Population,
                                  data_PREF_three$Generation),length)
mean(resume_design[,1], na.rm = TRUE)/3
mean(resume_design[,2], na.rm = TRUE)/3

resume_design<-tapply(data_PERF$Nb_eggs,list(data_PERF$Population,
                                  data_PERF$Generation),length)
mean(resume_design[,1], na.rm = TRUE)/3
mean(resume_design[,2], na.rm = TRUE)/3

dim(data_PREF_three)
dim(data_PREF)
head(data_PREF)


levels(data_PREF$Population)
```

## Plot
```{r }
acp_Rate_G0 <- plot_acp(dataset = data_PERF_Rate,
         formula="asin(sqrt(Rate)) ~ Test_environment + log(Nb_eggs)",
         gen = "G0",
         titleplot = "Offspring performance in G0")
acp_Rate_G2 <- plot_acp(dataset = data_PERF_Rate,
         formula="asin(sqrt(Rate)) ~ Test_environment + log(Nb_eggs)",
         gen = "G2",
         titleplot = "Offspring performance in G2")


acp_pref_G0 <- plot_acp(dataset = data_PREF_three,
         formula="log(Nb_eggs+1) ~ Test_environment ",
         gen = "G0",
         titleplot = "Oviposition preference in G0")
acp_pref_G2 <- plot_acp(dataset = data_PREF_three,
         formula="log(Nb_eggs+1) ~ Test_environment ",
         gen = "G2",
         titleplot = "Oviposition preference in G2")

acp_stim_G0 <- plot_acp(dataset = data_PERF,
         formula="log(Nb_eggs+1) ~ Test_environment ",
         gen = "G0",
         titleplot = "Oviposition stimulation in G0")
acp_stim_G2 <- plot_acp(dataset = data_PERF,
         formula="log(Nb_eggs+1) ~ Test_environment ",
         gen = "G2",
         titleplot = "Oviposition stimulation in G2")



legend <- lemon::g_legend(acp_pref_G0)


ACP_ALL <- cowplot::ggdraw() + 
  cowplot::draw_plot(acp_pref_G0 + theme(legend.position = "none"), 
            x = 0.01, y = 0.5, width = 0.25, height = 0.5) + 
  cowplot::draw_plot( acp_stim_G0+ theme(legend.position = "none"), 
            x = 0.31, y = 0.5, width = 0.25, height = 0.5) + 
  cowplot::draw_plot(acp_Rate_G0 + theme(legend.position = "none"), 
            x = 0.61, y = 0.5, width = 0.25, height = 0.5) + 
  cowplot::draw_plot(legend, x = 0.93, y = 0.5, width = 0.0001, height = 0.0001) + 
  cowplot::draw_plot(acp_pref_G2 + theme(legend.position = "none"), 
            x = 0.01, y = 0, width = 0.25, height = 0.5) + 
  cowplot::draw_plot(acp_stim_G2 + theme(legend.position = "none"), 
            x = 0.31, y = 0, width = 0.25, height = 0.5) + 
  cowplot::draw_plot(acp_Rate_G2 + theme(legend.position = "none"), 
            x = 0.61, y = 0, width = 0.25, height = 0.5) + 
  cowplot::draw_plot_label(c(" ", "A", "B", "C", " ",
                    " ", "D", "E", "F", " "),  
                  x = c(0.4, 0.01, 0.30, 0.61, 0.92, 0.4, 0.01, 0.3, 0.61, 0.92), 
                  y = c(1, 0.98, 0.98, 0.98, 0.98, 0.5, 0.48, 0.48, 0.48, 0.48), 
                  hjust = c(0,0,0,0,0,0,0,0,0,0), 
                  vjust = c(1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5),
                  size = 16) 
 ACP_ALL
 

cowplot::save_plot(file =here::here("figures", "ACP_pop.pdf"),
                  ACP_ALL,
                   base_height = 16/cm(1), base_width = 30/cm(1), dpi = 610)



```


