---
title: "Correlation between generations"
author: "Laure Olazcuaga, Nicolas Rode"
date: "`r format(Sys.Date(), '%d-%B-%Y')`"
output: 
  html_document:
    theme: "journal"
    toc: true
    toc_depth: 3
    number_sections: true
    toc_float:
      collapsed: false
      smooth_scroll: false
editor_options: 
  chunk_output_type: console
---


```{r setup, include =FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
devtools::load_all()
```


# DATA 
```{r }
#############################
#PERFORMANCE 
#############################

data_PERF <- import_data(dataset = "DATACOMPLET_PERF.csv", 
                         trait = "performance",
                         remove_testenvt = c("Grape","GF"), 
                         remove_pop = c("WT3"), 
                         remove_rate = NA)

head(data_PERF)
tapply(data_PERF$Nb_adults,list(data_PERF$Original_environment,data_PERF$Generation),length)

#############################
#EMERGENCE RATE
#############################

data_PERF_Rate <- import_data(dataset = "DATACOMPLET_PERF.csv", 
                         trait = "performance",
                         remove_testenvt = c("Grape","GF"), 
                         remove_pop = c("WT3"), 
                         remove_rate = "Replace")
head(data_PERF_Rate)
tapply(data_PERF_Rate$Nb_adults,list(data_PERF_Rate$Original_environment,
                                     data_PERF_Rate$Generation),length)

tapply(data_PERF_Rate$Rate,data_PERF_Rate$Generation,mean)

## To test Rate higher than 1
# data_PERF_Rate <- import_data(dataset = "DATACOMPLET_PERF.csv", 
#                          trait = "performance",
#                          remove_testenvt = c("Grape","GF"), 
#                          remove_pop = c("WT3"), 
#                          remove_rate = NA)
# #Replace Rate>1 by 1
# data_PERF_Rate$Rate[data_PERF_Rate$Nb_adults>=data_PERF_Rate$Nb_eggs] <- 1

###########################
#PREFERENCE 
###########################
data_PREF <- import_data(dataset = "DATACOMPLET_PREF.csv", 
                         trait = "preference",
                         remove_testenvt = NA, 
                         remove_pop = c("WT3"), 
                         remove_rate = NA)

head(data_PREF)
tapply(data_PREF$Nb_eggs,list(data_PREF$Original_environment,data_PREF$Generation),length)



###########################
#PREFERENCE 3 fruits
###########################
levels_test<-levels(data_PREF$Test_environment)
levels_original<-levels(data_PREF$Original_environment)


data_PREF_three <- import_data(dataset = "DATACOMPLET_PREF.csv", 
                         trait = "preference",
                         remove_testenvt = usefun::outersect(levels_test, 
                                                             levels_original), 
                         remove_pop = c("WT3"), 
                         remove_rate = NA)

head(data_PREF_three)
tapply(data_PREF_three$Nb_eggs,list(data_PREF_three$Original_environment,
                                    data_PREF_three$Generation),length)

resume_design<-tapply(as.factor(data_PREF_three$BoxID),list(data_PREF_three$Population,
                                  data_PREF_three$Generation),length)
mean(resume_design[,1], na.rm = TRUE)/3
mean(resume_design[,2], na.rm = TRUE)/3

resume_design<-tapply(data_PERF$Nb_eggs,list(data_PERF$Population,
                                  data_PERF$Generation),length)
mean(resume_design[,1], na.rm = TRUE)/3
mean(resume_design[,2], na.rm = TRUE)/3

dim(data_PREF_three)
dim(data_PREF)
head(data_PREF)


levels(data_PREF$Population)
```



# CORRELATIONS BETWEEN GO and G2
## Plot
```{r }
### OFFSPRING PERFORMANCE 
dataselect <- data_PERF_Rate
axis <- c("Offspring performance G1","Offspring performance G3")
modelformula <- asin(sqrt(Rate))  ~   Test_environment + Generation + log(Nb_eggs) 

## Accounting for differences among original environments in G0
# modelformula <- asin(sqrt(Rate))  ~   Original_environment*Generation + Test_environment + Generation + log(Nb_eggs) 
PAIR_G0_G2_PERFORMANCE <- plot_correlation_meanresiduals(dataset = dataselect, 
                                              formula = modelformula, 
                                              envfactor="Generation", 
                                              additional_factor="Test_environment",
                                              original_environment="Original_environment", 
                                              col_original_environment= c("#301934",
                                                                          "#BC3C6D", "#3FAA96"),
                                              grp_cols=c("Population", "Original_environment",
                                                         "Test_environment","Generation"),
                                              facetwrap=FALSE, fixedxylim = FALSE, 
                                              xaxis_labelprint = axis[1], 
                                              yaxis_labelprint =  axis[2])

### STIMULATION
dataselect <- data_PERF
axis <- c("Fecundity G0","Fecundity G2")
modelformula <- log(Nb_eggs+1)  ~ Test_environment + Generation

## Accounting for differences among original environments in G0
#modelformula <- log(Nb_eggs+1)  ~ Original_environment*Generation + Test_environment 

###PLOT 
PAIR_G0_G2_STIMULATION <- plot_correlation_meanresiduals(dataset = dataselect, 
                                              formula = modelformula, 
                                              envfactor="Generation", 
                                              additional_factor="Test_environment",
                                              original_environment="Original_environment", 
                                              col_original_environment= c("#301934",
                                                                          "#BC3C6D", "#3FAA96"),
                                              grp_cols=c("Population", "Original_environment",
                                                         "Test_environment","Generation"),
                                              facetwrap=FALSE, fixedxylim = FALSE, 
                                              xaxis_labelprint = axis[1], 
                                              yaxis_labelprint =  axis[2])


### PREFERENCE
dataselect <- data_PREF_three
axis <- c("Oviposition preference G0","Oviposition preference G2")
modelformula <- log(Nb_eggs+1)  ~ Test_environment + Generation + BoxID
## Accounting for differences among original environments in G0
#modelformula <- log(Nb_eggs+1)  ~ Original_environment*Generation + Test_environment + Generation + BoxID
PAIR_G0_G2_PREFERENCE <- plot_correlation_meanresiduals(dataset = dataselect, 
                                              formula = modelformula, 
                                              envfactor="Generation", 
                                              additional_factor="Test_environment",
                                              original_environment="Original_environment", 
                                              col_original_environment= c("#301934",
                                                                          "#BC3C6D", "#3FAA96"),
                                              grp_cols=c("Population", "Original_environment",
                                                         "Test_environment","Generation"),
                                              facetwrap=FALSE, fixedxylim = FALSE, 
                                              xaxis_labelprint = axis[1], 
                                              yaxis_labelprint =  axis[2])


# title_plot <- "CorrelationsG0_G2_Oviposition_Stimulation.pdf"
# title_plot <- "CorrelationsG1_G3_Offspring_performance.pdf"
# title_plot <- "CorrelationsG0_G2_Oviposition_Preference.pdf"
 
legend <- lemon::g_legend(PAIR_G0_G2_PREFERENCE)



PAIR_G0_G2 <- cowplot::ggdraw() + 
  cowplot::draw_plot(PAIR_G0_G2_PREFERENCE + theme(legend.position = "none", 
                                        plot.title = element_blank()), 
            x = 0.01, y = 0, width = 0.25, height = 1) + 
  cowplot::draw_plot( PAIR_G0_G2_STIMULATION+ theme(legend.position = "none", 
                                        plot.title = element_blank()), 
            x = 0.31, y = 0, width = 0.25, height = 1) + 
  cowplot::draw_plot(PAIR_G0_G2_PERFORMANCE + theme(legend.position = "none", 
                                        plot.title = element_blank()), 
            x = 0.61, y = 0, width = 0.25, height = 1) + 
  cowplot::draw_plot(legend, x = 0.93, y = 0.5, width = 0.0000001, height = 0.0000001) + 
  cowplot::draw_plot_label(c("A", "B", "C", " "),  
                  x = c(0.01, 0.30, 0.61, 0.92), 
                  y = c(0.98, 0.98, 0.98, 0.98), 
                  hjust = c(0,0,0,0), 
                  vjust = c(1.5, 1.5, 1.5, 1.5),
                  size = 16) 
 PAIR_G0_G2
 

cowplot::save_plot(file =here::here("figures", "Supplements_FigS9_Correlation_G0_G2.pdf"),
                  PAIR_G0_G2,
                   base_height = 10/cm(1), base_width = 36/cm(1), dpi = 610)



```

## Analyses
```{r }

### OFFSPRING PERFORMANCE 
m00 <- lme4::lmer(asin(sqrt(Rate))  ~ Test_environment + log(Nb_eggs) +
                    (0+ lme4::dummy(Generation, "G0") |  Population) + 
                    (0+lme4::dummy(Generation, "G2") | Population), 
                  data=data_PERF_Rate, REML = TRUE)

m01 <- lme4::lmer(asin(sqrt(Rate))  ~ Test_environment + log(Nb_eggs)+ 
                    (0+ Generation | Population) ,
                  data=data_PERF_Rate, REML = TRUE)

summary(m00)
summary(m01)
MuMIn::model.sel(m00, m01)
##Cl:Performance in G0 and G2 are not correlated


### OVIPOSITION PREFERENCE
m00 <- lme4::lmer(log(Nb_eggs+1)  ~ Test_environment  + BoxID + 
                    (0+lme4::dummy(Generation, "G0")|Population) + 
                    (0+lme4::dummy(Generation, "G2")|Population),
                  data=data_PREF_three, REML = TRUE)

m01 <- lme4::lmer(log(Nb_eggs+1)  ~ Test_environment  + BoxID + 
                    (0+Generation|Population),
                  data=data_PREF_three, REML = TRUE)

summary(m00)
summary(m01)
MuMIn::model.sel(m00, m01)
##Cl:Performance in G0 and G2 are not correlated





### OVIPOSITION STIMULATION
m00 <- lme4::lmer(log(Nb_eggs+1)  ~ Test_environment   + 
                    (0+lme4::dummy(Generation, "G0")|Population) + 
                    (0+lme4::dummy(Generation, "G2")|Population),
                  data=data_PREF, REML = TRUE)

m01 <- lme4::lmer(log(Nb_eggs+1)  ~ Test_environment   + 
                    (0+Generation|Population),
                  data=data_PREF, REML = TRUE)

summary(m00)
summary(m01)
MuMIn::model.sel(m00, m01)
##Cl:Performance in G0 and G2 are not correlated



```
